# Generated by Django 4.2.2 on 2023-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atv1', models.CharField(max_length=50)),
                ('atv2', models.CharField(max_length=50)),
                ('atv3', models.CharField(max_length=50)),
                ('atv4', models.CharField(max_length=50)),
                ('atv5', models.CharField(max_length=50)),
                ('atv6', models.CharField(max_length=50)),
                ('atv7', models.CharField(max_length=50)),
                ('atv8', models.CharField(max_length=50)),
            ],
        ),
    ]
