# Generated by Django 4.2.2 on 2023-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
